[tool.poetry]
name = "aws-eventbridge"
version = "0.1.0"
description = ""
authors = ["SÃ©rgio Rafael Siqueira <osergiosiqueira@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
boto3 = "^1.24.83"
aws-lambda-powertools = "^1.29.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
